SectionVerb {
	EnableSequence [
		# Enable Tertiary I2S mixer on MultiMedia1
		cset "name='TERT_MI2S_RX Audio Mixer MultiMedia1' 1"

		# WCD9380 RX/TX on MultiMedia2 and MultiMedia3
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 1"
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia3' 1"
	]

	DisableSequence [
		# Disable Tertiary I2S mixer on MultiMedia1
		cset "name='TERT_MI2S_RX Audio Mixer MultiMedia1' 0"

		# WCD9380 RX/TX off MultiMedia2 and MultiMedia3
		cset "name='MultiMedia2 Mixer TX_CODEC_DMA_TX_3' 0"
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia3' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker playback"

	Value {
		PlaybackPriority 150
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
	}
}

SectionDevice."Mic1" {
	Comment "Stereo Microphones"

	EnableSequence [
		# speaker-mic
		cset "name='TX DEC0 MUX' MSM_DMIC"
		cset "name='TX DMIC MUX0' DMIC1"
		cset "name='TX_AIF1_CAP Mixer DEC0' 1"
	]

	DisableSequence [
		# speaker-mic
		cset "name='TX DMIC MUX0' ZERO"
		cset "name='TX_AIF1_CAP Mixer DEC0' 0"
	]

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId},1"
		CaptureMixer "hw:${CardId}"
	}
}
