[General]
DisplayServer=x11
InputMethod=qtvirtualkeyboard
Numlock=off
GreeterEnvironment=QT_IM_MODULE=qtvirtualkeyboard,QT_SCALE_FACTOR=2,QT_AUTO_SCREEN_SCALE_FACTOR=0

[Theme]
Current=op8-breeze

[Users]
MinimumUid=1000

[Wayland]
SessionDir=/usr/local/share/wayland-sessions,/usr/share/wayland-sessions
